services:
  postgres:
    image: postgres:16-alpine
    container_name: planet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: planet
      POSTGRES_PASSWORD: planet1234
      POSTGRES_DB: planet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  # 선택

volumes:
  postgres_data: